CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar_path VARCHAR(255),
    company VARCHAR(255),
    country VARCHAR(255),
    created_at TIMESTAMP(6),
    email VARCHAR(255),
    firstname VARCHAR(255),
    is_active BOOLEAN,
    last_download_messages TIMESTAMP(6),
    last_download_pictures TIMESTAMP(6),
    last_login TIMESTAMP(6),
    lastname VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    sharingchoice BOOLEAN
);

CREATE TABLE tracks (
    id VARCHAR(255) PRIMARY KEY,
    color VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE session_header (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    end_time TIMESTAMP(6),
    host VARCHAR(255),
    is_published BOOLEAN,
    location VARCHAR(255),
    name VARCHAR(255),
    start_time TIMESTAMP(6),
    type VARCHAR(255),
    track_id VARCHAR(255),
    CONSTRAINT fk_session_track FOREIGN KEY (track_id) REFERENCES tracks(id)
);

CREATE TABLE session_content (
    id BIGINT PRIMARY KEY,
    content CLOB,
    CONSTRAINT fk_session_content_header FOREIGN KEY (id) REFERENCES session_header(id)
);

CREATE TABLE session_likes (
    sessionheader_id INTEGER NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_session_likes_user FOREIGN KEY (sessionheader_id) REFERENCES users(id),
    CONSTRAINT fk_session_likes_session FOREIGN KEY (user_id) REFERENCES session_header(id)
);

CREATE TABLE gallery_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    like_count INTEGER NOT NULL,
    path VARCHAR(255),
    upload_time TIMESTAMP(6),
    owner INTEGER,
    CONSTRAINT fk_gallery_owner FOREIGN KEY (owner) REFERENCES users(id)
);

CREATE TABLE image_likes (
    image_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT fk_image_likes_image FOREIGN KEY (image_id) REFERENCES gallery_images(id),
    CONSTRAINT fk_image_likes_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_time TIMESTAMP(6),
    text VARCHAR(255),
    title VARCHAR(255),
    author INTEGER,
    CONSTRAINT fk_message_author FOREIGN KEY (author) REFERENCES users(id)
);

CREATE TABLE read_messages (
    user_id INTEGER NOT NULL,
    message_id INTEGER NOT NULL,
    CONSTRAINT fk_read_messages_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_read_messages_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);

CREATE TABLE admin_messages (
    id VARCHAR(255) PRIMARY KEY,
    email_sent BOOLEAN,
    message CLOB,
    priority VARCHAR(255) NOT NULL,
    push_sent BOOLEAN,
    read_count INTEGER,
    recipient_count INTEGER,
    recipient_type VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP(6) NOT NULL,
    sent_by VARCHAR(255),
    title VARCHAR(255) NOT NULL
);

CREATE TABLE admin_message_recipients (
    message_id VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT fk_admin_recipients_message FOREIGN KEY (message_id) REFERENCES admin_messages(id),
    CONSTRAINT fk_admin_recipients_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE admin_message_read_by (
    message_id VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT fk_admin_read_message FOREIGN KEY (message_id) REFERENCES admin_messages(id),
    CONSTRAINT fk_admin_read_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE content (
    id VARCHAR(255) PRIMARY KEY,
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    content_key VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    updated_by VARCHAR(255),
    content_value CLOB
);

CREATE TABLE navigation_config (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP(6),
    icon VARCHAR(100) NOT NULL,
    is_enabled BOOLEAN NOT NULL,
    label_key VARCHAR(100) NOT NULL,
    required_role VARCHAR(50),
    route VARCHAR(255) NOT NULL,
    sort_order INTEGER NOT NULL,
    tab_key VARCHAR(50) NOT NULL UNIQUE,
    updated_at TIMESTAMP(6)
);

CREATE TABLE pages (
    id UUID PRIMARY KEY,
    content CLOB,
    created_at TIMESTAMP(6),
    icon VARCHAR(100),
    is_public BOOLEAN NOT NULL,
    is_published BOOLEAN NOT NULL,
    label VARCHAR(50),
    label_color VARCHAR(20),
    layout_id INTEGER NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6),
    created_by INTEGER,
    updated_by INTEGER,
    CONSTRAINT fk_page_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_page_updater FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE page_messages (
    id UUID PRIMARY KEY,
    content CLOB NOT NULL,
    created_at TIMESTAMP(6),
    sort_order INTEGER NOT NULL,
    page_id UUID NOT NULL,
    CONSTRAINT fk_page_message_page FOREIGN KEY (page_id) REFERENCES pages(id)
);

CREATE TABLE localized_content (
    id UUID PRIMARY KEY,
    content_key VARCHAR(255) NOT NULL,
    content_type VARCHAR(20),
    content_value CLOB NOT NULL,
    created_at TIMESTAMP(6),
    language_code VARCHAR(10) NOT NULL,
    updated_at TIMESTAMP(6),
    updated_by INTEGER,
    CONSTRAINT uk_localized_content UNIQUE (content_key, language_code),
    CONSTRAINT fk_localized_content_updater FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE site_config (
    id UUID PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_type VARCHAR(20) NOT NULL,
    config_value CLOB,
    created_at TIMESTAMP(6),
    description VARCHAR(500),
    is_public BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6),
    updated_by INTEGER,
    CONSTRAINT fk_site_config_updater FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE locations (
    id VARCHAR(255) PRIMARY KEY,
    capacity INTEGER,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE media (
    id UUID PRIMARY KEY,
    alt_text VARCHAR(255),
    category VARCHAR(50),
    created_at TIMESTAMP(6),
    file_size BIGINT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    uploaded_by INTEGER,
    CONSTRAINT fk_media_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id)
);
