CREATE TABLE agenda_push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    endpoint VARCHAR(2048) NOT NULL UNIQUE,
    p256dh VARCHAR(255) NOT NULL,
    auth_secret VARCHAR(255) NOT NULL,
    locale VARCHAR(16) NOT NULL DEFAULT 'en',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_agenda_push_subscription_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE agenda_reminder_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    delivered_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_agenda_reminder_delivery UNIQUE (subscription_id, session_id),
    CONSTRAINT fk_agenda_reminder_delivery_subscription
        FOREIGN KEY (subscription_id) REFERENCES agenda_push_subscriptions(id) ON DELETE CASCADE,
    CONSTRAINT fk_agenda_reminder_delivery_session
        FOREIGN KEY (session_id) REFERENCES session_header(id) ON DELETE CASCADE
);
